blank_issues_enabled: false
contact_links:
  - name: Help channel
    about: You can ask for help with the bot in this Discord channel. If you are not in the Discord server you wont be able to see this chanenl.
    url: https://canary.discord.com/channels/1327443750276042793/1333006187230269500
