name: Critical issue
description: This form is for critical issues with the bot or related features that require immediate attention.
title: "[CRITICAL] "
labels: ["bug"]
assignees: ["EmilyxFox"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections to help reproduce and fix the issue.
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      placeholder: "When I do this, this unexpected thing happens..."
    validations:
      require: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. send ping command
        2. pass "test string" in "heartbeat" field
        2. crash
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot or video (optional)
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
  - type: markdown
    attributes: Thanks for reporting this issue!
