name: "✨ Feature request"
description: This form is for requesting features and changes to the bot.
title: "feature title..."
labels: ["enhancement"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      placeholder: "a new command that does something crazy!"
    validations:
      require: true
  - type: checkboxes
    id: terms
    attributes:
      label: Extras
      options:
        - label: I have checked that an issue for this feature doesn't already exist
          required: true
        - label: I want to work on this feature
  - type: markdown
    attributes:
      value: Thanks for suggesting this feature!
